import { getBot, updateBot } from '../database/index.js';

// Get environment variables for a bot
export const getEnv = async (botId) => {
  const bot = await getBot(botId);
  if (!bot) throw new Error('Bot not found');
  
  let env = {};
  try {
    env = bot.environment ? JSON.parse(bot.environment) : {};
  } catch (e) {
    env = {};
  }
  
  return {
    botId,
    botName: bot.display_name || bot.name,
    variables: env,
    count: Object.keys(env).length
  };
};

// Set environment variables for a bot
export const setEnv = async (botId, variables) => {
  const bot = await getBot(botId);
  if (!bot) throw new Error('Bot not found');
  
  // Validate input
  if (typeof variables !== 'object' || Array.isArray(variables)) {
    throw new Error('Variables must be an object');
  }
  
  // Sanitize keys and values
  const sanitized = {};
  for (const [key, value] of Object.entries(variables)) {
    // Key must be alphanumeric + underscore
    const cleanKey = key.replace(/[^a-zA-Z0-9_]/g, '');
    if (cleanKey) {
      sanitized[cleanKey] = String(value);
    }
  }
  
  const envString = JSON.stringify(sanitized);
  await updateBot(botId, { environment: envString });
  
  return {
    botId,
    variables: sanitized,
    count: Object.keys(sanitized).length
  };
};

// Add or update single environment variable
export const setEnvVar = async (botId, key, value) => {
  const current = await getEnv(botId);
  const newVars = { ...current.variables };
  newVars[key] = String(value);
  return await setEnv(botId, newVars);
};

// Delete environment variable
export const deleteEnvVar = async (botId, key) => {
  const current = await getEnv(botId);
  const newVars = { ...current.variables };
  delete newVars[key];
  return await setEnv(botId, newVars);
};

// Bulk import from .env format
export const importEnv = async (botId, envText) => {
  const lines = envText.split('\n');
  const vars = {};
  
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    
    const match = trimmed.match(/^([^=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      const value = match[2].trim();
      // Remove quotes if present
      const cleanValue = value.replace(/^["']|["']$/g, '');
      vars[key] = cleanValue;
    }
  }
  
  return await setEnv(botId, vars);
};

// Export to .env format
export const exportEnv = async (botId) => {
  const current = await getEnv(botId);
  let result = '# Environment Variables for ' + current.botName + '\n';
  result += '# Generated by Rye Panel\n\n';
  
  for (const [key, value] of Object.entries(current.variables)) {
    result += `${key}="${value}"\n`;
  }
  
  return result;
};

export default {
  getEnv,
  setEnv,
  setEnvVar,
  deleteEnvVar,
  importEnv,
  exportEnv
};
